name: console
version: 3.0.0
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: Console Power Library
homepage: https://github.com/DirectMyFile/console.dart

environment:
  sdk: '>=2.0.0-dev.61 <3.0.0'

dependencies:
  vector_math: ^2.0.7

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
