name: console
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: "Console Power Library"
version: 2.0.1
homepage: https://github.com/DirectMyFile/console.dart
dev_dependencies:
  laser: any