name: console
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: "Console Power Library"
version: 2.1.0
homepage: https://github.com/DirectMyFile/console.dart
dependencies:
  quiver: '>=0.19.0 <0.20.0'
dev_dependencies:
  laser: any
environment:
  sdk: ">=1.8.1"