name: console
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: "Console Power Library"
version: 1.1.1
homepage: https://github.com/DirectMyFile/console.dart
dependencies:
  quiver: '>=0.18.2 <0.19.0'
