name: console
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: "Console Power Library"
version: 2.1.0
homepage: https://github.com/DirectMyFile/console.dart
dev_dependencies:
  laser: any
environment:
  sdk: ">=1.8.1"